{
 "title": "SonarQube",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Project",
    "query": "label_values(sonarqube_bugs, name)"
   }
  ]
 },
 "panels": [
  { "title": "${Project}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Project" },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$Project\"}"
    }
   ]
  },
  {
   "title": "Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$Project\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$Project\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$Project\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$Project\"}"
    }
   ]
  }
 ]
}